### ISSUE TITLE
Module not found: Error: Can't resolve 'core-js/modules/web.dom.iterable' in '/home/amir/Workspace/mmb/MMB-admin-frontend/node_modules/declarative-js/src/map'

### ISSUE THREAD

**Issue by amir-mmb** [pavel-surinin/declarativejs#2]
Refering to the documentation, at #GroupBy and Map

`
    const data = [
      { title: 'Predator', genre: 'sci-fi' },
      { title: 'Predator 2', genre: 'sci-fi' },
      { title: 'Alien vs Predator', genre: 'sci-fi' },
      { title: 'Tom & Jerry', genre: 'cartoon' }
    ]
    // data.reduce(groupBy(movie => move.genre), Map())
    let test = data.reduce(Reducer.groupBy('genre'), Reducer.Map());

`

`ERROR in ./node_modules/declarative-js/src/array/reduce.js
Module not found: Error: Can't resolve 'core-js/modules/es6.array.from' in '/home/amir/Workspace/mmb/MMB-admin-frontend/node_modules/declarative-js/src/array'
ERROR in ./node_modules/declarative-js/src/array/filters.js
Module not found: Error: Can't resolve 'core-js/modules/es6.array.iterator' in '/home/amir/Workspace/mmb/MMB-admin-frontend/node_modules/declarative-js/src/array'
ERROR in ./node_modules/declarative-js/src/array/reduce.js
Module not found: Error: Can't resolve 'core-js/modules/es6.array.iterator' in '/home/amir/Workspace/mmb/MMB-admin-frontend/node_modules/declarative-js/src/array'
ERROR in ./node_modules/declarative-js/src/array/mappers.js
Module not found: Error: Can't resolve 'core-js/modules/es6.array.iterator' in '/home/amir/Workspace/mmb/MMB-admin-frontend/node_modules/declarative-js/src/array'
ERROR in ./node_modules/declarative-js/src/map/JMap.js
Module not found: Error: Can't resolve 'core-js/modules/es6.array.iterator' in '/home/amir/Workspace/mmb/MMB-admin-frontend/node_modules/declarative-js/src/map'
ERROR in ./node_modules/declarative-js/src/map/JMap.js
Module not found: Error: Can't resolve 'core-js/modules/es6.object.assign' in '/home/amir/Workspace/mmb/MMB-admin-frontend/node_modules/declarative-js/src/map'
ERROR in ./node_modules/declarative-js/src/map/ImmutableBuilder.js
Module not found: Error: Can't resolve 'core-js/modules/es6.object.freeze' in '/home/amir/Workspace/mmb/MMB-admin-frontend/node_modules/declarative-js/src/map'
ERROR in ./node_modules/declarative-js/src/map/ImmutableMap.js
Module not found: Error: Can't resolve 'core-js/modules/es6.object.freeze' in '/home/amir/Workspace/mmb/MMB-admin-frontend/node_modules/declarative-js/src/map'
ERROR in ./node_modules/declarative-js/src/map/ImmutableMap.js
Module not found: Error: Can't resolve 'core-js/modules/es6.object.is-frozen' in '/home/amir/Workspace/mmb/MMB-admin-frontend/node_modules/declarative-js/src/map'
ERROR in ./node_modules/declarative-js/src/array/reduce.js
Module not found: Error: Can't resolve 'core-js/modules/es6.object.keys' in '/home/amir/Workspace/mmb/MMB-admin-frontend/node_modules/declarative-js/src/array'
ERROR in ./node_modules/declarative-js/src/array/mappers.js
Module not found: Error: Can't resolve 'core-js/modules/es6.object.keys' in '/home/amir/Workspace/mmb/MMB-admin-frontend/node_modules/declarative-js/src/array'
ERROR in ./node_modules/declarative-js/src/map/JMap.js
Module not found: Error: Can't resolve 'core-js/modules/es6.object.keys' in '/home/amir/Workspace/mmb/MMB-admin-frontend/node_modules/declarative-js/src/map'
ERROR in ./node_modules/declarative-js/src/internal/reducer.utils.js
Module not found: Error: Can't resolve 'core-js/modules/es6.object.seal' in '/home/amir/Workspace/mmb/MMB-admin-frontend/node_modules/declarative-js/src/internal'
ERROR in ./node_modules/declarative-js/src/map/ImmutableMap.js
Module not found: Error: Can't resolve 'core-js/modules/es6.reflect.get' in '/home/amir/Workspace/mmb/MMB-admin-frontend/node_modules/declarative-js/src/map'
ERROR in ./node_modules/declarative-js/src/array/reduce.js
Module not found: Error: Can't resolve 'core-js/modules/es6.regexp.to-string' in '/home/amir/Workspace/mmb/MMB-admin-frontend/node_modules/declarative-js/src/array'
ERROR in ./node_modules/declarative-js/src/array/filters.js
Module not found: Error: Can't resolve 'core-js/modules/es6.set' in '/home/amir/Workspace/mmb/MMB-admin-frontend/node_modules/declarative-js/src/array'
ERROR in ./node_modules/declarative-js/src/array/filters.js
Module not found: Error: Can't resolve 'core-js/modules/es6.string.iterator' in '/home/amir/Workspace/mmb/MMB-admin-frontend/node_modules/declarative-js/src/array'
ERROR in ./node_modules/declarative-js/src/array/reduce.js
Module not found: Error: Can't resolve 'core-js/modules/es6.string.iterator' in '/home/amir/Workspace/mmb/MMB-admin-frontend/node_modules/declarative-js/src/array'
ERROR in ./node_modules/declarative-js/src/array/filters.js
Module not found: Error: Can't resolve 'core-js/modules/es6.symbol' in '/home/amir/Workspace/mmb/MMB-admin-frontend/node_modules/declarative-js/src/array'
ERROR in ./node_modules/declarative-js/src/array/reduce.js
Module not found: Error: Can't resolve 'core-js/modules/es6.symbol' in '/home/amir/Workspace/mmb/MMB-admin-frontend/node_modules/declarative-js/src/array'
ERROR in ./node_modules/declarative-js/src/internal/groupBy.js
Module not found: Error: Can't resolve 'core-js/modules/es6.symbol' in '/home/amir/Workspace/mmb/MMB-admin-frontend/node_modules/declarative-js/src/internal'
ERROR in ./node_modules/declarative-js/src/internal/reducer.utils.js
Module not found: Error: Can't resolve 'core-js/modules/es6.symbol' in '/home/amir/Workspace/mmb/MMB-admin-frontend/node_modules/declarative-js/src/internal'
ERROR in ./node_modules/declarative-js/src/map/ImmutableMap.js
Module not found: Error: Can't resolve 'core-js/modules/es6.symbol' in '/home/amir/Workspace/mmb/MMB-admin-frontend/node_modules/declarative-js/src/map'
ERROR in ./node_modules/declarative-js/src/array/filters.js
Module not found: Error: Can't resolve 'core-js/modules/es7.symbol.async-iterator' in '/home/amir/Workspace/mmb/MMB-admin-frontend/node_modules/declarative-js/src/array'
ERROR in ./node_modules/declarative-js/src/array/reduce.js
Module not found: Error: Can't resolve 'core-js/modules/es7.symbol.async-iterator' in '/home/amir/Workspace/mmb/MMB-admin-frontend/node_modules/declarative-js/src/array'
ERROR in ./node_modules/declarative-js/src/internal/groupBy.js
Module not found: Error: Can't resolve 'core-js/modules/es7.symbol.async-iterator' in '/home/amir/Workspace/mmb/MMB-admin-frontend/node_modules/declarative-js/src/internal'
ERROR in ./node_modules/declarative-js/src/internal/reducer.utils.js
Module not found: Error: Can't resolve 'core-js/modules/es7.symbol.async-iterator' in '/home/amir/Workspace/mmb/MMB-admin-frontend/node_modules/declarative-js/src/internal'
ERROR in ./node_modules/declarative-js/src/map/ImmutableMap.js
Module not found: Error: Can't resolve 'core-js/modules/es7.symbol.async-iterator' in '/home/amir/Workspace/mmb/MMB-admin-frontend/node_modules/declarative-js/src/map'
ERROR in ./node_modules/declarative-js/src/array/filters.js
Module not found: Error: Can't resolve 'core-js/modules/web.dom.iterable' in '/home/amir/Workspace/mmb/MMB-admin-frontend/node_modules/declarative-js/src/array'
ERROR in ./node_modules/declarative-js/src/array/reduce.js
Module not found: Error: Can't resolve 'core-js/modules/web.dom.iterable' in '/home/amir/Workspace/mmb/MMB-admin-frontend/node_modules/declarative-js/src/array'
ERROR in ./node_modules/declarative-js/src/array/mappers.js
Module not found: Error: Can't resolve 'core-js/modules/web.dom.iterable' in '/home/amir/Workspace/mmb/MMB-admin-frontend/node_modules/declarative-js/src/array'
ERROR in ./node_modules/declarative-js/src/map/JMap.js
Module not found: Error: Can't resolve 'core-js/modules/web.dom.iterable' in '/home/amir/Workspace/mmb/MMB-admin-frontend/node_modules/declarative-js/src/map'
`

**Comment by pavel-surinin** [comment]
Hi, @amir-mmb , thanks for raising up this issue. I've added "_core-js_" to peer dependencies in version _3.8.5_. So now it works.
